### ISSUE TITLE
[MODELO DE PÁGINA PADRÃO] Criar modelo de página padrão para conteúdos das páginas

### ISSUE THREAD

**Issue by estercmandrade** [Ethos-ti/SiteEthos#10]
## SOBRE - https://ethos.hacklab.com.br/instituto-ethos/
**Página com blocos gutenberg editáveis pelo cliente**

- [x] UX: deixar modo de edição da tela próximo ao modo de visualização (baixa prioridade, caso necessário)

- [x] Botão Apresentação pdf do instituto ethos deve direcionar para: https://www.ethos.org.br/wp-content/uploads/2020/03/Apresenta%C3%A7%C3%A3o_Institucional_2020-Atualiza%C3%A7%C3%A3o_03.02.pdf

- [x] Botão acesse o código de conduta do ethos deve direcionar para: https://www3.ethos.org.br/wp-content/uploads/2018/04/C%C3%B3digo-de-Conduta_A4_links.pdf

- [x] Botão acesse a página de prestação de contas irá direcionar para a Página de Prestação de Contas

- [x] Aplicar widget de parcerias/apoio desenvolvido na #14 

Layout Desktop: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?type=design&node-id=202-345&t=qtbX0ktYB5KmqClv-0&scaling=min-zoom&page-id=112%3A2

Layout Mobile: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?type=design&node-id=1838-18488&t=qtbX0ktYB5KmqClv-0&scaling=min-zoom&page-id=112%3A2

#

## PRESTAÇÃO DE CONTAS - https://ethos.hacklab.com.br/prestacao-de-contas/

- [x] Dropdown de prestação de contas deve ser um bloco gutenberg (confirmar)

- [x] Aplicar widget de parcerias/apoio desenvolvido na #14 

Deste modo o cliente conseguirá adicionar demais itens ao longo do tempo

Layout desktop: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?type=design&node-id=203-6&t=fvqaDCWrjlv8agOo-0&scaling=min-zoom&page-id=112%3A2

Layout mobile: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?type=design&node-id=1838-18425&t=fvqaDCWrjlv8agOo-0&scaling=min-zoom&page-id=112%3A2

#

## EQUIPE - https://ethos.hacklab.com.br/equipe/
A página Equipe possui três abas, cada qual com seu conteúdo

- [x] Utilizar plugin Essential Blocks para estrutura de abas
- Abas: governança, gestão e participação social
- confirmar com gestão ao implementar, para o caso de haver mudança de plugin
- [x] Utilizar widget de parcerias/apoio #14 
- [x] Imagem dos avatares não deve ficar distorcida ou em baixa qualidade (a não ser que a própria imagem tenha baixa qualidade)
- [x] "Mostrar Mais" terá comportamento de sanfona, ao clicar ele deve mostrar o resto do resumo

- Atenção ao alinhamento da tabela da aba participação social

Layout Governança - desktop: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?type=design&node-id=202-1308&t=4VXQQQ6WQ8tiCTWj-0&scaling=min-zoom&page-id=112%3A2
Layout Governança - mobile

Layout Gestão - desktop: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?type=design&node-id=202-1571&t=4VXQQQ6WQ8tiCTWj-0&scaling=min-zoom&page-id=112%3A2
Layout Gestão - mobile: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?type=design&node-id=1838-18705&t=4VXQQQ6WQ8tiCTWj-0&scaling=min-zoom&page-id=112%3A2

Layout Participação Social - desktop: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?type=design&node-id=204-207&t=4VXQQQ6WQ8tiCTWj-0&scaling=min-zoom&page-id=112%3A2
Layout Participação Social - mobile: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?type=design&node-id=1838-18756&t=4VXQQQ6WQ8tiCTWj-0&scaling=min-zoom&page-id=112%3A2

**Comment by caio-ascava** [comment]
Considerar apenas ajustes mobile:

- [ ] 1. Ajustar bloco com "nome, cargo e icone linkedin" conforme Figma e em relação ao tamanho do avatar.

![Image](https://github.com/Ethos-ti/SiteEthos/assets/151761173/f10c61d8-7fbb-479d-96ef-9c11e4af70ab)

- [ ] 2. Ajustar texto dentro do bloco, alinhado a margem esquerda. Atualmente está centralizado.

![Image](https://github.com/Ethos-ti/SiteEthos/assets/151761173/1d483584-f5fd-45c9-b7e3-725bf85c13de)

- [ ] Ajustar tabela via mobile, pois está quebrando:

![Image](https://github.com/Ethos-ti/SiteEthos/assets/151761173/a9cc142a-3510-41e0-a0f5-950e844149a9)
