### ISSUE TITLE
[PÁGINAS] Criar páginas de CURSOS, NOSSAS ASSOCIADAS, ETHOS SERVIÇO e DIÁLOGO ETHOS

### ISSUE THREAD

**Issue by daphnemartinsba** [Ethos-ti/SiteEthos#16]
## CURSOS

- [x] Botão: Acesse a lista de cursos disponíveis deve direcionar para a archive de cursos
- [x] Utilizar widget de parcerias/apoio #14 

Layout desktop: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?type=design&node-id=316-2890&t=uGWdeOWPugFnaHVN-0&scaling=min-zoom&page-id=112%3A2

Layout mobile: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?type=design&node-id=1838-19068&t=uGWdeOWPugFnaHVN-0&scaling=min-zoom&page-id=112%3A2

# 

## NOSSAS ASSOCIADAS 

- [x] logos devem ser editáveis - utilizar blocos
- [x] Utilizar widget de parcerias/apoio #14 
- link do vídeo: https://www.youtube.com/watch?v=ZAs91QegXzo
- link de _saiba como se associar e conheça nossos planos._ : direcionar para associe-se

Layout desktop: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?type=design&node-id=353-3889&t=uGWdeOWPugFnaHVN-0&scaling=min-zoom&page-id=112%3A2

Layout mobile: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?type=design&node-id=1838-17760&t=uGWdeOWPugFnaHVN-0&scaling=min-zoom&page-id=112%3A2

# 

## ETHOS SERVIÇO
A página possui um bloco que terá três abas: Educação executiva, Consultorias, Estudos e pesquisas

- [x] Inserir textos nas abas Educação executiva e Estudos e pesquisas com base no layout de Consultorias

- Site antigo com textos: https://www.ethos.org.br/conteudo/ethos-servicos// 

Layout de consultorias:

![Image](https://github.com/Ethos-ti/SiteEthos/assets/75261677/9ed73a14-1c3a-47bb-b103-59985ccbd400)

Textos de Educação executiva:

![Image](https://github.com/Ethos-ti/SiteEthos/assets/75261677/14a3fd0a-ff1f-477c-b588-8b0eeef4c576)

Textos de Estudos e pesquisas:

![Image](https://github.com/Ethos-ti/SiteEthos/assets/75261677/648d66cb-1662-4544-90ae-944bbab76455)

- [x] Utilizar widget de parcerias/apoio #14 

Layout desktop: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?type=design&node-id=329-2880&t=uGWdeOWPugFnaHVN-0&scaling=min-zoom&page-id=112%3A2

Layout mobile: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?type=design&node-id=1838-19400&t=uGWdeOWPugFnaHVN-0&scaling=min-zoom&page-id=112%3A2

#

## DIÁLOGOS ETHOS 
Essa página possui 3 abas: Rodas de diálogo, Conversa com Lideranças, Conexão Ethos

- [x] Abas devem ser um bloco do gutenberg,utilizar plugin essential blocks (confirmar antes se o plugin permanecerá sendo esse)

- [x] Utilizar widget de parcerias/apoio #14 
- [x] na Aba conexão ethos:
- Link Curitiba 2019 deve direcionar para: https://www.ethos.org.br/conteudo/conexoes/conexoes-ethos/conexoes-ethos-curitiba/
- Link Belo Horizonte 2019 deve direcionar para: https://www.ethos.org.br/conteudo/conexoes/conexoes-ethos/conexoes-ethos-belo-horizonte/

Layout Rodas de diálogo - desktop: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?type=design&node-id=340-5504&t=uGWdeOWPugFnaHVN-0&scaling=min-zoom&page-id=112%3A2
Layout Rodas de diálogo - mobile: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?type=design&node-id=1838-19472&t=uGWdeOWPugFnaHVN-0&scaling=min-zoom&page-id=112%3A2

Layout Conversa com Lideranças - desktop: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?type=design&node-id=351-2972&t=uGWdeOWPugFnaHVN-0&scaling=min-zoom&page-id=112%3A2
Layout Conversa com Lideranças - mobile: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?type=design&node-id=1838-19445&t=uGWdeOWPugFnaHVN-0&scaling=min-zoom&page-id=112%3A2

Layout Rodas de diálogo - desktop: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?type=design&node-id=351-3112&t=uGWdeOWPugFnaHVN-0&scaling=min-zoom&page-id=112%3A2
Layout Rodas de diálogo - mobile: https://www.figma.com/proto/HJanIoNJS8SynxptNSqcji/Ethos-UI?type=design&node-id=1838-19498&t=uGWdeOWPugFnaHVN-0&scaling=min-zoom&page-id=112%3A2

**Comment by barbaburns** [comment]
Não encontrei todos os logos de empresas para subir no conteudo da galeria em Nossas Associadas.

**Comment by caio-ascava** [comment]
- [ ] 1- Alterar fonte para 16px size e 24px line height
- [ ] 2- Line height para 28.8px
- [ ] 3- Alterar line height para 21px e botão deve ter uma espaçamento maior, para ficar igual ao Figma
- [ ] 4- Alterar para 20px size e 30px line height
- [ ] 5- Alterar line height para 28.8px
- [ ] 6- Esta ultima frase possui um tamanho diferente do texto, pelo Figma, 20px size e 30px line height.

![Image](https://github.com/Ethos-ti/SiteEthos/assets/151761173/e86d7233-6b72-4fb2-93d0-1b917f5800cd)

- [ ] 1. Conheça as associadas: Esta frase, está em negrito (bold), sendo tambem necessario aumentar line height para 30
- [ ] 2. Correção de escrita: Associadas
- [ ] 3. Alterar line height para 30px

![Image](https://github.com/Ethos-ti/SiteEthos/assets/151761173/ae9e3baf-27bf-4186-a868-23b376b5ae3a)

**Comment by daphnemartinsba** [comment]
Ícone de Nossas Associadas estão disponíveis em produção: https://www.ethos.org.br/conteudo/associados/

**Comment by barbaburns** [comment]
em Dialogos mobile: 8- Diminuir recuo entre blocos. ficou acertado com pedro.lucas que o espaçamento que ja esta aplicado será o padrão. nem todas as areas do figma esta atualizado com isso.

**Comment by barbaburns** [comment]
ETHOS SERVIÇO (mobile) : estao ocorrendo algumas inconsistencias de layout. por exemplo o paragrafo em destaque esta com font 16px nas outras paginas e apenas nessa esta com font 20px. vou manter font 16px de acordo com as outras.

**Comment by barbaburns** [comment]
DIÁLOGO ETHOS (Mobile) - as abas em mobile, ela são um elemento scroll, então quando clica na aba ela não centraliza automaticamente. precisa dar scroll. eu entendo que o comportamento esperado é esse mesmo.



![Image](https://github.com/Ethos-ti/SiteEthos/assets/11669690/cff8a98a-2766-4ce6-8268-629f79765c3e)

**Comment by daphnemartinsba** [comment]
Página NOSSAS ASSOCIADAS será concluída na issue #67
