### ISSUE TITLE
[DESIGN TOKENS]

### ISSUE THREAD

**Issue by daphnemartinsba** [Ethos-ti/SiteEthos#7]
# Variáveis

## Font Weight
- [x] `$font-weight--bold` - 700
- [x]  `$font-weight--regular` - 600
- [x] `$font-weight--regular` - 400
- [x] `$font-weight--light` - 300

## Font Family
- [x] `$font-family--primary` - 'Open Sans'
- [x] `$font-family--secondary` - 'Montserrat'

## Line-Heights
- [x] `$line-height--loose` : 1.75;
- [x] `$line-height--normal` : 1.5;
- [x] `$line-height--tight`: 1.25;
- [x] `$line-height--none` : 1;
- [x] `$line-height--squeeze` : 0.9;
- [x] `$line-height-auto`: auto;

### Feedback colors
- [x] Warning pure - #DC052D
- [x] Warning light - #FB4B6C
- [x] Warning dark - #780318
- [x] Helper pure - #9ACA3C
- [x] Helper light - #C3DF8B
- [x] Helper dark - #5E7C22

### Neutral Colors
- [x] Low pure - #222222
- [x] Low light - #7d7d7d
- [x] Low dark - #363B43
- [x] High pure - #FFFFFF
- [x] High light - #F2F3F4
- [x] High dark - #DDDDDD

### Brand Colors
- [x] Primary pure - #0091d7
- [x] primary light - #A8DFF4
- [x] primary dark - #0075AD

### Secondary colors
- [x] Meio Ambiente - #B7C726
- [x] Meio ambiente Light - #EEF721
- [x] Meio Ambiente Dark - #A6AD06
- [x] Integridade - #0083a2
- [x] Integridade Light - #00B2EB
- [x] Integridade Dark - #006484
- [x] Gestão sustentável - #f7971c
- [x] Gestão sustentável Light - #FFB04D
- [x] Gestão sustentável Dark - #E37F00
- [x] Economia - #07b79c
- [x] Economia light - #25F3D2
- [x] Economia Dark - #09A88E
- [x] Direitos Humanos - #ed164e
- [x] Direitos Humanos Light - #FF3D74
- [x] Direitos Humanos Dark - #D7003D

### Font Sizes

- [x] font-size hero - 4rem  
- [x] font-size xxx-large - 3rem
- [x] font-size xx-large - 2rem
- [x] font-size x-large - 1.5rem
- [x] font-size large - 1.25rem
- [x] font-size medium - 1rem
- [x] font-size small - 0.875rem
- [x]  font-size x-small - 0.75rem

 
### Breakpoints

- [x] `$break--small`: 34rem; // 544px
- [x] `$break--tablet`: 37.5rem; // 600px
- [x] `$break--desktop`: 48rem; // 768px
- [x] `$break--desktop-large`: 75rem; // 1200px
- [x] `$break--desktop-x-large`: 87.5rem; // 1400px

### Grid
- [x] `$grid--wide`: 75rem;
- [x] `$grid--normal`: 48rem;
- [x] `$grid--narrow`: 37.5rem;

### Gaps
- [x] `$gap--x-small`: 0.25rem;
- [x] `$gap--small`: 0.5rem;
- [x] `$gap--medium`: 1rem;
- [x] `$gap--large`: 2rem;
- [x] `$gap--x-large`: 2.5rem;
- [x] `$gap--xx-large`: 3rem;
- [x] `$gap--xxx-large`: 4rem;
- [x] `$gap--huge`: 5rem;
- [x] `$gap--giant`: 8rem;

### Border-radius
- [x] $border-radius--pilled: 80px;
- [x] $border-radius--round: 50%;
- [x] $border-radius--large: 16px;
- [x] $border-radius--medium: 8px;
- [x] $border-radius--small: 4px;
- [x] $border-radius--none: 0;

### Border Width
- [x] $border-width--small: 1px;
- [x] $border-width--medium: 2px;
- [x] $border-width--large: 3px;
- [x] $border-width--x-large: 4px;

**Comment by daphnemartinsba** [comment]
blocked: aguardando a atualização do layout

**Comment by daphnemartinsba** [comment]
> blocked: aguardando a atualização do layout

Layout foi atualizado, precisa ser validado

**Comment by daphnemartinsba** [comment]
#### Secondary Colors

- [ ] Alterar Gestão Sustentável Light para #FFC275

#### Font Family
- [ ] alterar fontfamily para:
"fontFamilies": [
{
"name": "Primária",
"slug": "primary",
"fontFamily": "'Montserrat', sans-serif"
},
{
"name": "Secundária",
"slug": "secondary",
"fontFamily": "Open Sans', sans-serif"
},
{
"name": "Título",
"slug": "heading",
"fontFamily": "'Montserrat', sans-serif"
}
]
